### ISSUE TITLE
Drag feature in Firefox doesn't appear to work.

### ISSUE THREAD

**Issue by othmanabdulsalam** [fireship-io/framer-demo#1]
I tried using the website inside Google Chrome and Mozilla Firefox. The drag feature worked in Chrome, but not in Firefox. What kind of fix would make it work in Firefox, as I am interested in potentially using framer for a learning project.

**Comment by klutchdev** [comment]
Hmm... I did a bunch of digging to try and find some documentation on this, and I can't find anything related. 
Is the demo itself not dragging properly? Is there any type of movement at all from the component, or does it just stay fixed in place?

**Comment by othmanabdulsalam** [comment]
This is a screenshot of what I see on Firefox when i try to click and drag the GIF.

![image](https://user-images.githubusercontent.com/59613149/134712231-944b4c2e-45aa-4f6a-897c-8689b57dd87c.png)
